wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1723486007
    t:
      1:
      - 1
      - 41
      - 43
      - 55
      - 63
      3:
      - 13
      - 16
      4: 3.8.19
      5: 0.12.20
      8:
      - 5
      - 9
cfg_file:
  desc: null
  value: /home/liwa/project/OneFormer/detectron2/projects/Panoptic-DeepLab/configs/yeast_panoptics/city_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024_yeast.yaml
model:
  desc: null
  value:
    ANCHOR_GENERATOR:
      ANGLES:
      - - -90
        - 0
        - 90
      ASPECT_RATIOS:
      - - 0.5
        - 1.0
        - 2.0
      NAME: DefaultAnchorGenerator
      OFFSET: 0.0
      SIZES:
      - - 32
        - 64
        - 128
        - 256
        - 512
    BACKBONE:
      FREEZE_AT: 0
      NAME: build_resnet_deeplab_backbone
    DEVICE: cuda
    FPN:
      FUSE_TYPE: sum
      IN_FEATURES: []
      NORM: ''
      OUT_CHANNELS: 256
    INS_EMBED_HEAD:
      ASPP_CHANNELS: 256
      ASPP_DILATIONS:
      - 6
      - 12
      - 18
      ASPP_DROPOUT: 0.1
      CENTER_LOSS_WEIGHT: 2000.0
      COMMON_STRIDE: 4
      CONVS_DIM: 128
      HEAD_CHANNELS: 32
      IN_FEATURES:
      - res2
      - res3
      - res5
      NAME: PanopticDeepLabInsEmbedHead
      NORM: SyncBN
      OFFSET_LOSS_WEIGHT: 0.01
      PROJECT_CHANNELS:
      - 32
      - 64
      PROJECT_FEATURES:
      - res2
      - res3
    IS_DEMO: false
    IS_TRAIN: true
    KEYPOINT_ON: false
    LOAD_PROPOSALS: false
    MASK_ON: false
    META_ARCHITECTURE: PanopticDeepLab
    PANOPTIC_DEEPLAB:
      BENCHMARK_NETWORK_SPEED: false
      CENTER_THRESHOLD: 0.1
      NMS_KERNEL: 7
      PREDICT_INSTANCES: true
      SIZE_DIVISIBILITY: 512
      STUFF_AREA: 2048
      TOP_K_INSTANCE: 200
      USE_DEPTHWISE_SEPARABLE_CONV: false
    PANOPTIC_FPN:
      COMBINE:
        ENABLED: true
        INSTANCES_CONFIDENCE_THRESH: 0.5
        OVERLAP_THRESH: 0.5
        STUFF_AREA_LIMIT: 4096
      INSTANCE_LOSS_WEIGHT: 1.0
    PIXEL_MEAN:
    - 102.364
    - 102.364
    - 102.364
    PIXEL_STD:
    - 23.532
    - 23.532
    - 23.532
    PROPOSAL_GENERATOR:
      MIN_SIZE: 0
      NAME: RPN
    RESNETS:
      DEFORM_MODULATED: false
      DEFORM_NUM_GROUPS: 1
      DEFORM_ON_PER_STAGE:
      - false
      - false
      - false
      - false
      DEPTH: 50
      NORM: SyncBN
      NUM_GROUPS: 1
      OUT_FEATURES:
      - res2
      - res3
      - res5
      RES2_OUT_CHANNELS: 256
      RES4_DILATION: 1
      RES5_DILATION: 2
      RES5_MULTI_GRID:
      - 1
      - 2
      - 4
      STEM_OUT_CHANNELS: 128
      STEM_TYPE: deeplab
      STRIDE_IN_1X1: false
      WIDTH_PER_GROUP: 64
    RETINANET:
      BBOX_REG_LOSS_TYPE: smooth_l1
      BBOX_REG_WEIGHTS:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      FOCAL_LOSS_ALPHA: 0.25
      FOCAL_LOSS_GAMMA: 2.0
      IN_FEATURES:
      - p3
      - p4
      - p5
      - p6
      - p7
      IOU_LABELS:
      - 0
      - -1
      - 1
      IOU_THRESHOLDS:
      - 0.4
      - 0.5
      NMS_THRESH_TEST: 0.5
      NORM: ''
      NUM_CLASSES: 9
      NUM_CONVS: 4
      PRIOR_PROB: 0.01
      SCORE_THRESH_TEST: 0.05
      SMOOTH_L1_LOSS_BETA: 0.1
      TOPK_CANDIDATES_TEST: 1000
    ROI_BOX_CASCADE_HEAD:
      BBOX_REG_WEIGHTS:
      - - 10.0
        - 10.0
        - 5.0
        - 5.0
      - - 20.0
        - 20.0
        - 10.0
        - 10.0
      - - 30.0
        - 30.0
        - 15.0
        - 15.0
      IOUS:
      - 0.5
      - 0.6
      - 0.7
    ROI_BOX_HEAD:
      BBOX_REG_LOSS_TYPE: smooth_l1
      BBOX_REG_LOSS_WEIGHT: 1.0
      BBOX_REG_WEIGHTS:
      - 10.0
      - 10.0
      - 5.0
      - 5.0
      CLS_AGNOSTIC_BBOX_REG: false
      CONV_DIM: 256
      FC_DIM: 1024
      FED_LOSS_FREQ_WEIGHT_POWER: 0.5
      FED_LOSS_NUM_CLASSES: 9
      NAME: ''
      NORM: ''
      NUM_CONV: 0
      NUM_FC: 0
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      POOLER_TYPE: ROIAlignV2
      SMOOTH_L1_BETA: 0.0
      TRAIN_ON_PRED_BOXES: false
      USE_FED_LOSS: false
      USE_SIGMOID_CE: false
    ROI_HEADS:
      BATCH_SIZE_PER_IMAGE: 512
      IN_FEATURES:
      - res4
      IOU_LABELS:
      - 0
      - 1
      IOU_THRESHOLDS:
      - 0.5
      NAME: Res5ROIHeads
      NMS_THRESH_TEST: 0.5
      NUM_CLASSES: 9
      POSITIVE_FRACTION: 0.25
      PROPOSAL_APPEND_GT: true
      SCORE_THRESH_TEST: 0.05
    ROI_KEYPOINT_HEAD:
      CONV_DIMS:
      - 512
      - 512
      - 512
      - 512
      - 512
      - 512
      - 512
      - 512
      LOSS_WEIGHT: 1.0
      MIN_KEYPOINTS_PER_IMAGE: 1
      NAME: KRCNNConvDeconvUpsampleHead
      NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: true
      NUM_KEYPOINTS: 17
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      POOLER_TYPE: ROIAlignV2
    ROI_MASK_HEAD:
      CLS_AGNOSTIC_MASK: false
      CONV_DIM: 256
      NAME: MaskRCNNConvUpsampleHead
      NORM: ''
      NUM_CONV: 0
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      POOLER_TYPE: ROIAlignV2
    RPN:
      BATCH_SIZE_PER_IMAGE: 256
      BBOX_REG_LOSS_TYPE: smooth_l1
      BBOX_REG_LOSS_WEIGHT: 1.0
      BBOX_REG_WEIGHTS:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      BOUNDARY_THRESH: -1
      CONV_DIMS:
      - -1
      HEAD_NAME: StandardRPNHead
      IN_FEATURES:
      - res4
      IOU_LABELS:
      - 0
      - -1
      - 1
      IOU_THRESHOLDS:
      - 0.3
      - 0.7
      LOSS_WEIGHT: 1.0
      NMS_THRESH: 0.7
      POSITIVE_FRACTION: 0.5
      POST_NMS_TOPK_TEST: 1000
      POST_NMS_TOPK_TRAIN: 2000
      PRE_NMS_TOPK_TEST: 6000
      PRE_NMS_TOPK_TRAIN: 12000
      SMOOTH_L1_BETA: 0.0
    SEM_SEG_HEAD:
      ASPP_CHANNELS: 256
      ASPP_DILATIONS:
      - 6
      - 12
      - 18
      ASPP_DROPOUT: 0.1
      COMMON_STRIDE: 4
      CONVS_DIM: 256
      HEAD_CHANNELS: 256
      IGNORE_VALUE: 255
      IN_FEATURES:
      - res2
      - res3
      - res5
      LOSS_TOP_K: 0.2
      LOSS_TYPE: hard_pixel_mining
      LOSS_WEIGHT: 10.0
      NAME: PanopticDeepLabSemSegHead
      NORM: SyncBN
      NUM_CLASSES: 9
      PROJECT_CHANNELS:
      - 32
      - 64
      PROJECT_FEATURES:
      - res2
      - res3
      USE_DEPTHWISE_SEPARABLE_CONV: false
    WEIGHTS: detectron2://DeepLab/R-52.pkl
solver:
  desc: null
  value:
    AMP:
      ENABLED: false
    BASE_LR: 0.0005
    BASE_LR_END: 0.0
    BIAS_LR_FACTOR: 1.0
    CHECKPOINT_PERIOD: 5000
    CLIP_GRADIENTS:
      CLIP_TYPE: value
      CLIP_VALUE: 1.0
      ENABLED: false
      NORM_TYPE: 2.0
    GAMMA: 0.1
    IMS_PER_BATCH: 32
    LR_SCHEDULER_NAME: WarmupPolyLR
    MAX_ITER: 200000
    MOMENTUM: 0.9
    NESTEROV: false
    NUM_DECAYS: 3
    OPTIMIZER: ADAM
    POLY_LR_CONSTANT_ENDING: 0.0
    POLY_LR_POWER: 0.9
    REFERENCE_WORLD_SIZE: 0
    RESCALE_INTERVAL: false
    STEPS:
    - 30000
    WARMUP_FACTOR: 0.001
    WARMUP_ITERS: 1000
    WARMUP_METHOD: linear
    WEIGHT_DECAY: 0.0
    WEIGHT_DECAY_BIAS: 0.0
    WEIGHT_DECAY_NORM: 0.0
